repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format --check
        language: system
        files: \.py$
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        files: \.py$
      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        pass_filenames: false