openapi: 3.1.0
info:
  title: Goals Management API
  version: 0.1.0
  description: |
    REST API for managing personal goals (MVP).
    Supports CRUD operations, filtering by completion status, and server-side persistence.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/goals:
    get:
      summary: List all goals
      operationId: listGoals
      tags:
        - goals
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [active, done]
          description: Filter goals by completion status (active = not done, done = completed)
      responses:
        '200':
          description: List of goals, sorted by (is_done ASC, date_updated DESC)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoalListResponse'
        '400':
          description: Invalid query parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create a new goal
      operationId: createGoal
      tags:
        - goals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoalCreateRequest'
      responses:
        '201':
          description: Goal created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoalResponse'
        '422':
          description: Validation error (empty title, title too long)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/goals/{id}:
    get:
      summary: Get a single goal by ID
      operationId: getGoal
      tags:
        - goals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Goal unique identifier
      responses:
        '200':
          description: Goal found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoalResponse'
        '404':
          description: Goal not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: Update a goal (title and/or completion status)
      operationId: updateGoal
      tags:
        - goals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Goal unique identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoalUpdateRequest'
      responses:
        '200':
          description: Goal updated successfully (date_updated refreshed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoalResponse'
        '404':
          description: Goal not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error (empty title, title too long, no fields provided)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a goal permanently
      operationId: deleteGoal
      tags:
        - goals
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Goal unique identifier
      responses:
        '204':
          description: Goal deleted successfully (no content)
        '404':
          description: Goal not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GoalCreateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Goal title (1-255 characters, non-empty after trim)
          example: "Complete project documentation"

    GoalUpdateRequest:
      type: object
      minProperties: 1
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: New goal title (optional, 1-255 characters)
          example: "Updated project documentation"
        is_done:
          type: boolean
          description: Completion status (optional)
          example: true

    GoalResponse:
      type: object
      required:
        - id
        - title
        - is_done
        - date_created
        - date_updated
      properties:
        id:
          type: string
          format: uuid
          description: Unique goal identifier (auto-generated)
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          maxLength: 255
          description: Goal title
          example: "Complete project documentation"
        is_done:
          type: boolean
          description: Completion status (false = active, true = done)
          example: false
        date_created:
          type: string
          format: date-time
          description: ISO 8601 timestamp when goal was created
          example: "2025-10-04T14:30:00Z"
        date_updated:
          type: string
          format: date-time
          description: ISO 8601 timestamp of last modification
          example: "2025-10-04T15:45:00Z"

    GoalListResponse:
      type: object
      required:
        - goals
      properties:
        goals:
          type: array
          items:
            $ref: '#/components/schemas/GoalResponse'
          description: List of goals, sorted by (is_done ASC, date_updated DESC)

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Title cannot be empty or whitespace-only"
        type:
          type: string
          description: Error type identifier
          example: "validation_error"
        status:
          type: integer
          description: HTTP status code
          example: 422
