openapi: 3.1.0
info:
  title: Milestones API
  version: 0.1.0
  description: |
    Public HTTP contract for Milestones module.
    Placeholder stub — to be filled during /module-implement.
servers:
  - url: http://localhost:8000
    description: Local development server
security: []
paths: {}
components:
  schemas: {}
